Repository dolittle/Studio, pull requests merged in 2021-09, with the labels that each got.

#109 WIP: Issue with images via docker image
  Source/SelfService/Web/webpack.config.ts
Labels: patch

#108 Fix the COPY TO CLIPBOARD button to actually work in POAPI creation view
  Source/SelfService/Web/microservice/purchaseOrder/overview.tsx
Labels: patch

#112 Add release label checker workflow
  .github/workflows/check_labels.yml
Labels: no-release

#111 Add snackbar when copying POapi webhook urls.
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/microservice/purchaseOrder/overview.tsx
  Source/SelfService/Web/package.json
Labels: minor

#110 Bug fix white name++
  Documentation/k3d.md
  Source/SelfService/Web/microservice/Microservice.tsx
  Source/SelfService/Web/microservice/purchaseOrder/configuration.tsx
  Source/SelfService/Web/microservice/purchaseOrder/container.tsx
  Source/SelfService/Web/microservice/purchaseOrder/purchaseorder.scss
  Source/SelfService/Web/microservice/purchaseOrder/view.tsx
  Source/SelfService/Web/utils/materialUi.tsx
Labels: patch

#114 Remove the views that allow creation of a RawDataLog
  Source/SelfService/Web/microservice/Microservice.tsx
  Source/SelfService/Web/microservice/rawDataLog/config/create.tsx
Labels: minor

#116 Hide rawdatalog delete
  Makefile
  Source/SelfService/Web/microservice/microservice.scss
  Source/SelfService/Web/microservice/overview.tsx
  Source/SelfService/Web/microservice/viewCard.tsx
  Source/SelfService/Web/stores/microservice.ts
Labels: minor

#117 Add error handling to POAPI creation and display error with snackbar
  Source/SelfService/Web/api/api.ts
  Source/SelfService/Web/microservice/purchaseOrder/container.tsx
  Source/SelfService/Web/stores/microservice.ts
Labels: patch

#119 Add a storage class and persistent volume and docs
  Documentation/k3d.md
  Environment/k3d/k8s/persistent-volume.yml
  Environment/k3d/k8s/storage-class.yml
Labels: no-release
