Repository dolittle/Studio, pull requests merged in 2022-06, with the labels that each got.

#197 Microservice dropdown, view in absolute date range and timestamps for Logs
  Source/SelfService/Web/logging/lineParsing.ts
  Source/SelfService/Web/logging/logFilter/activeFilters.tsx
  Source/SelfService/Web/logging/logFilter/dateRangeFilter.tsx
  Source/SelfService/Web/logging/logFilter/filterSelect.tsx
  Source/SelfService/Web/logging/logFilter/logFilterPanel.tsx
  Source/SelfService/Web/logging/logFilter/microserviceFilter.tsx
  Source/SelfService/Web/logging/logLine.tsx
  Source/SelfService/Web/logging/logLines.tsx
  Source/SelfService/Web/logging/logPanel.tsx
  Source/SelfService/Web/logging/logPanelAbsolute.tsx
  Source/SelfService/Web/logging/logPanelRelative.tsx
  Source/SelfService/Web/logging/loki/logLines.ts
  Source/SelfService/Web/logging/loki/parsing.ts
  Source/SelfService/Web/logging/loki/queries.ts
  Source/SelfService/Web/logging/loki/types.ts
  Source/SelfService/Web/logging/loki/useLogsFromLast.ts
  Source/SelfService/Web/logging/loki/useLogsFromRange.ts
  Source/SelfService/Web/package.json
  Source/SelfService/Web/screens/logsScreen.tsx
  Source/SelfService/Web/theme/buttonText.tsx
  Source/SelfService/Web/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: minor

#198 Only show microservices in current env in filter
  Source/SelfService/Web/screens/logsScreen.tsx
Labels: patch

#202 Fix-edit-date-range-crash-app
  Source/SelfService/Web/logging/logFilter/dateRangeFilter.tsx
Labels: patch

#203 SelfService Backend mock for logs
  .gitignore
  .vscode/launch.json
  Environment/mock/.eslintrc.js
  Environment/mock/api/applications/index.js
  Environment/mock/index.js
  Environment/mock/middlewares.js
  Environment/mock/monitoring/logs/generated.js
  Environment/mock/monitoring/logs/index.js
  Environment/mock/package.json
  Environment/mock/yarn.lock
  Source/SelfService/Web/logging/loki/useLogsFromLast.ts
Labels: no-release

#204 Show shimmering lines while fetching log lines
  Environment/mock/monitoring/logs/generated.js
  Environment/mock/monitoring/logs/index.js
  Source/SelfService/Web/logging/logLine.tsx
  Source/SelfService/Web/logging/logPanel.tsx
  Source/SelfService/Web/logging/loki/useLogsFromLast.ts
  Source/SelfService/Web/logging/loki/useLogsFromRange.ts
  Source/SelfService/Web/logging/shimmeringLogLines.tsx
Labels: patch

#205 Load more logs with "infinite scrolling" when viewing date-range logs
  Source/SelfService/Web/logging/logPanel.tsx
  Source/SelfService/Web/logging/logPanelAbsolute.tsx
  Source/SelfService/Web/logging/logPanelRelative.tsx
  Source/SelfService/Web/package.json
  Source/SelfService/Web/screens/logsScreen.tsx
  yarn.lock
Labels: minor

#206 Keep Logs screen filter state in URL so it can be shared (and reloaded), and keep it when switching environments.
  Environment/mock/api/applications/index.js
  Environment/mock/monitoring/logs/generated.js
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/admin/application/view.tsx
  Source/SelfService/Web/application/applicationsChanger.tsx
  Source/SelfService/Web/containerregistry/tags.tsx
  Source/SelfService/Web/customer/view.tsx
  Source/SelfService/Web/logging/logFilter/useLogFilters.ts
  Source/SelfService/Web/m3connector/details.tsx
  Source/SelfService/Web/m3connector/setup.tsx
  Source/SelfService/Web/package.json
  Source/SelfService/Web/screens/logsScreen.tsx
  Source/SelfService/Web/utils/route.ts
  yarn.lock
Labels: minor

#209 Update studio header information
  Source/SelfService/Web/images/favicon.png
  Source/SelfService/Web/webpack.config.ts
  Source/Shared/Web/webpack/plugins.ts
Labels: patch

#212 Changed favicon.png to ico format
  Source/SelfService/Web/images/favicon.ico
  Source/SelfService/Web/images/favicon.png
  Source/Shared/Web/webpack/plugins.ts
Labels: no-release
