Repository dolittle/Studio, pull requests merged in 2022-08, with the labels that each got.

#228 Usability improvements for environment variables page
  Source/SelfService/Web/microservice/environmentVariables/view.tsx
Labels: patch

#224 Microservices cards
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/application/applicationsChanger.tsx
  Source/SelfService/Web/layout/breadcrumbs.scss
  Source/SelfService/Web/layout/breadcrumbs.tsx
  Source/SelfService/Web/layout/layout.scss
  Source/SelfService/Web/microservice/create.tsx
  Source/SelfService/Web/microservice/create/card.tsx
  Source/SelfService/Web/microservice/dataTable.tsx
  Source/SelfService/Web/microservice/deployButton.tsx
  Source/SelfService/Web/microservice/microservice.scss
  Source/SelfService/Web/microservice/microservice.tsx
  Source/SelfService/Web/microservice/microserviceViewScreen.tsx
  Source/SelfService/Web/microservice/noMicroservices.tsx
  Source/SelfService/Web/microservice/overview.tsx
  Source/SelfService/Web/package.json
  Source/SelfService/Web/screens/microservicesScreen.tsx
  Source/SelfService/Web/theme/theme.ts
  yarn.lock
Labels: minor

#230 Fix data table
  Source/SelfService/Web/microservice/dataTable.tsx
Labels: patch

#193 start stop k3d scripts
  Documentation/k3d.md
Labels: no-release

#231 Select application page
  .babelrc.js
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/index.ejs
  Source/SelfService/Web/index.scss
  Source/SelfService/Web/index.tsx
  Source/SelfService/Web/layout/loginWrapper.tsx
  Source/SelfService/Web/resource-imports.d.ts
  Source/SelfService/Web/screens/applicationsScreen.tsx
  Source/SelfService/Web/screens/applicationsScreen/actionButtons.tsx
  Source/SelfService/Web/screens/applicationsScreen/applicationsList.tsx
  Source/SelfService/Web/screens/applicationsScreen/applicationsScreen.tsx
  Source/SelfService/Web/screens/applicationsScreen/createButton.tsx
  Source/SelfService/Web/theme/assets/images.d.ts
  Source/SelfService/Web/theme/assets/logos/logo.svg
  Source/SelfService/Web/theme/assets/logos/logos.tsx
  Source/SelfService/Web/theme/assets/logos/symbol.svg
  Source/SelfService/Web/webpack.config.ts
  Source/Shared/Web/package.json
  Source/Shared/Web/svgr/convert-svg-to-box-plugin.ts
  Source/Shared/Web/svgr/loader.ts
  Source/Shared/Web/svgr/template.ts
Labels: patch

#229 Ordered environment variables in edit page
  Source/SelfService/Web/microservice/environmentVariables/view.tsx
Labels: patch

#235 Configure caching of the SelfService/Web server
  Source/SelfService/Web/.docker/custom-entrypoint.sh
  Source/SelfService/Web/.docker/nginx.conf
  Source/SelfService/Web/Dockerfile
Labels: patch

#236 Cleanup <head> tags and remove manifest.json
  Source/SelfService/Web/index.ejs
  Source/SelfService/Web/manifest.json
Labels: patch

#233 Capitalize first letter in runtime vs
  Source/SelfService/Web/microservice/dataTable.tsx
Labels: patch

#237 Prevent exceptions if runtimeVersion is not found
  Source/SelfService/Web/microservice/dataTable.tsx
Labels: patch
