Repository dolittle/Studio, pull requests merged in 2022-04, with the labels that each got.

#168 Create private microservice UI
  Source/SelfService/Web/api/api.ts
  Source/SelfService/Web/api/index.ts
  Source/SelfService/Web/microservice/base/create.tsx
  Source/SelfService/Web/microservice/base/view.tsx
  Source/SelfService/Web/stores/microservice.ts
  Source/SelfService/Web/theme/dropDownMenu.tsx
  Source/SelfService/Web/theme/switch.tsx
  Source/SelfService/Web/theme/textField.tsx
Labels: minor

#172 Making admin work in the local cluster
  Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/customer.json
  Environment/k3d/k8s/api-v1.yml
Labels: minor

#175 resolutions are not working, or i am failing to use them correctly :P
  Source/SelfService/Web/package.json
  Source/Shared/Web/package.json
  package.json
  yarn.lock
Labels: no-release

#171 Admin view to list / add / remove users from an application
  Source/SelfService/Web/admin/application/view.tsx
  Source/SelfService/Web/api/application.ts
  Source/SelfService/Web/api/customer.ts
  Source/SelfService/Web/api/studio.ts
  Source/SelfService/Web/customer/view.tsx
  Source/SelfService/Web/screens/adminScreen.tsx
Labels: patch

#180 Make the TextField for arguments not required
  Source/SelfService/Web/microservice/components/headArguments.tsx
Labels: patch

#177 Fix the `reset-local-k3d` command
  Environment/k3d/reset-local-k3d
Labels: no-release

#174 Bringing connections to the application
  Source/SelfService/Web/api/application.ts
  Source/SelfService/Web/api/index.ts
  Source/SelfService/Web/microservice/base/create.tsx
  Source/SelfService/Web/microservice/base/view.tsx
Labels: minor
