Repository dolittle/Studio, pull requests merged in 2022-03, with the labels that each got.

#160 Fix k3d docs and local dev env
  Documentation/k3d.md
  Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/11b6cf47-5d9f-438f-8116-0d9828654657/application.json
  Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/11b6cf47-5d9f-438f-8116-0d9828654657/dev/placeholder.txt
  Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/11b6cf47-5d9f-438f-8116-0d9828654657/terraform.json
  Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/studio.json
  Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/tenant.json
Labels: no-release

#161 Enabled can_create_application for local dev env
  Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/studio.json
Labels: no-release

#159 Add new customer view
  Source/SelfService/Web/api/customer.ts
  Source/SelfService/Web/api/studio.ts
  Source/SelfService/Web/customer/view.tsx
  Source/SelfService/Web/customer/viewAll.tsx
  Source/SelfService/Web/screens/adminScreen.tsx
  Source/Shared/Web/package.json
  yarn.lock
Labels: minor

#164 Add CodeClimate badges for easier access to it and to track progress
  README.md
Labels: no-release

#163 Fix direct links with environment not working
  Source/SelfService/Web/businessMoments/container.tsx
  Source/SelfService/Web/businessMoments/overview.tsx
  Source/SelfService/Web/components/pickEnvironment.tsx
  Source/SelfService/Web/screens/backupsScreen.tsx
  Source/SelfService/Web/screens/businessMomentsScreen.tsx
  Source/SelfService/Web/screens/documentationScreen.tsx
  Source/SelfService/Web/screens/insightsScreen.tsx
  Source/SelfService/Web/screens/microservicesScreen.tsx
  Source/SelfService/Web/screens/withRouteApplicationState.tsx
  Source/SelfService/Web/utils/route.ts
Labels: patch

#167 Fix microservice creation and request to default to public
  Source/SelfService/Web/api/index.ts
  Source/SelfService/Web/microservice/base/create.tsx
  Source/SelfService/Web/microservice/base/view.tsx
Labels: patch
