Repository dolittle/Studio, pull requests merged in 2022-05, with the labels that each got.

#179 addd x/sys to sum and mod files for Selfervice Backend
  Source/SelfService/Backend/go.mod
  Source/SelfService/Backend/go.sum
Labels: patch, dependencies

#176 Update to latest Material UI v5 and supporting dependencies
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/admin/application/view.tsx
  Source/SelfService/Web/application/applicationsChanger.tsx
  Source/SelfService/Web/application/create.tsx
  Source/SelfService/Web/backup/listView.tsx
  Source/SelfService/Web/components/accountSettingsMenu.tsx
  Source/SelfService/Web/components/alertBox.tsx
  Source/SelfService/Web/components/dieAndRestart.tsx
  Source/SelfService/Web/components/notfound.tsx
  Source/SelfService/Web/components/pickEnvironment.tsx
  Source/SelfService/Web/components/topNavBar.tsx
  Source/SelfService/Web/components/topRightMenu.tsx
  Source/SelfService/Web/customer/create.tsx
  Source/SelfService/Web/customer/view.tsx
  Source/SelfService/Web/documentation/cicd/setupAzurePipelines.tsx
  Source/SelfService/Web/index.tsx
  Source/SelfService/Web/microservice/base/configView.tsx
  Source/SelfService/Web/microservice/base/create.tsx
  Source/SelfService/Web/microservice/base/liveIngressView.tsx
  Source/SelfService/Web/microservice/base/view.tsx
  Source/SelfService/Web/microservice/components/downloadButtons.tsx
  Source/SelfService/Web/microservice/components/headArguments.tsx
  Source/SelfService/Web/microservice/components/headDataRow.tsx
  Source/SelfService/Web/microservice/create.tsx
  Source/SelfService/Web/microservice/create/card.tsx
  Source/SelfService/Web/microservice/delete.tsx
  Source/SelfService/Web/microservice/environmentVariables/view.tsx
  Source/SelfService/Web/microservice/purchaseOrder/configuration.tsx
  Source/SelfService/Web/microservice/purchaseOrder/create.tsx
  Source/SelfService/Web/microservice/purchaseOrder/dataStateIcon.tsx
  Source/SelfService/Web/microservice/purchaseOrder/editWebhookCredentials.tsx
  Source/SelfService/Web/microservice/purchaseOrder/erpIcon.tsx
  Source/SelfService/Web/microservice/purchaseOrder/rowWithLink.tsx
  Source/SelfService/Web/microservice/purchaseOrder/view.tsx
  Source/SelfService/Web/microservice/purchaseOrder/viewConfiguration.tsx
  Source/SelfService/Web/microservice/purchaseOrder/viewWebhookCredentials.tsx
  Source/SelfService/Web/microservice/view/healthStatus.tsx
  Source/SelfService/Web/package.json
  Source/SelfService/Web/screens/themeScreen.tsx
  Source/SelfService/Web/stores/notifications.tsx
  Source/SelfService/Web/theme/button.tsx
  Source/SelfService/Web/theme/buttonText.tsx
  Source/SelfService/Web/theme/downloadButton.tsx
  Source/SelfService/Web/theme/dropDownMenu.tsx
  Source/SelfService/Web/theme/switch.tsx
  Source/SelfService/Web/theme/tabs.tsx
  Source/SelfService/Web/theme/textField.tsx
  Source/SelfService/Web/theme/theme.ts
  Source/SelfService/Web/utils/materialUi.tsx
  Source/Shared/Web/package.json
  package.json
  yarn.lock
Labels: minor

#181 Removed menu item for Business Moments
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/api/businessmoments.ts
  Source/SelfService/Web/api/index.ts
  Source/SelfService/Web/businessMoments/businessMomentEditor.tsx
  Source/SelfService/Web/businessMoments/container.tsx
  Source/SelfService/Web/businessMoments/createCard.tsx
  Source/SelfService/Web/businessMoments/editor.tsx
  Source/SelfService/Web/businessMoments/entityEditor.tsx
  Source/SelfService/Web/businessMoments/overview.tsx
  Source/SelfService/Web/businessMoments/viewCard.tsx
  Source/SelfService/Web/layout/layoutWithSidebar.tsx
  Source/SelfService/Web/microservice/businessMomentsAdaptor/configuration/RestConfiguration.tsx
  Source/SelfService/Web/microservice/businessMomentsAdaptor/configuration/WebhooksConfiguration.tsx
  Source/SelfService/Web/microservice/businessMomentsAdaptor/create.tsx
  Source/SelfService/Web/microservice/businessMomentsAdaptor/view.tsx
  Source/SelfService/Web/microservice/create.tsx
  Source/SelfService/Web/microservice/view.tsx
  Source/SelfService/Web/microservice/viewCard.tsx
  Source/SelfService/Web/screens/businessMomentsScreen.tsx
  Source/SelfService/Web/screens/loginScreen.tsx
  Source/SelfService/Web/stores/businessmoment.ts
  Source/SelfService/Web/stores/microservice.ts
  Source/SelfService/Web/stores/state.ts
Labels: minor

#185 Unique applications with their environments
  Source/SelfService/Web/customer/view.tsx
Labels: patch

#182 View Container registry
  .codeclimate.yml
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/api/containerregistry.ts
  Source/SelfService/Web/containerregistry/container.tsx
  Source/SelfService/Web/containerregistry/images.tsx
  Source/SelfService/Web/containerregistry/tags.tsx
  Source/SelfService/Web/containerregistry/welcome.tsx
  Source/SelfService/Web/documentation/accessContainerRegistry.tsx
  Source/SelfService/Web/layout/layoutWithSidebar.tsx
  Source/SelfService/Web/screens/containerRegistryScreen.tsx
Labels: minor

#184 Feature mount config files
  Source/SelfService/Web/api/api.ts
  Source/SelfService/Web/microservice/base/components/configFilesTable.tsx
  Source/SelfService/Web/microservice/base/configView.tsx
  Source/SelfService/Web/microservice/base/configuration.tsx
  Source/SelfService/Web/microservice/base/liveIngressView.tsx
  Source/SelfService/Web/microservice/base/view.tsx
  Source/SelfService/Web/microservice/components/downloadButtons.tsx
  Source/SelfService/Web/microservice/view.tsx
  Source/SelfService/Web/theme/downloadButton.tsx
  Source/SelfService/Web/theme/selectFileConfirmationModal.tsx
  Source/SelfService/Web/theme/selectFileModal.tsx
Labels: minor

#187 fix changelog for mounting files
  Source/SelfService/Web/CHANGELOG.md
Labels: no-release

#188 Fix firefox file upload
  Source/SelfService/Web/microservice/base/components/fileUploadForm.tsx
  Source/SelfService/Web/microservice/base/configuration.tsx
  Source/SelfService/Web/theme/selectFileModal.tsx
Labels: patch

#190 Change to trigger build
  Source/SelfService/Web/api/m3connector.ts
Labels: minor

#191 m3connector details screen on click, reveal the contents
  Source/SelfService/Web/m3connector/details.tsx
Labels: minor

#192 Feature-apply-theming
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/admin/application/view.tsx
  Source/SelfService/Web/application/building.tsx
  Source/SelfService/Web/application/create.tsx
  Source/SelfService/Web/backup/viewCard.tsx
  Source/SelfService/Web/components/dieAndRestart.tsx
  Source/SelfService/Web/components/notfound.tsx
  Source/SelfService/Web/components/pickEnvironment.tsx
  Source/SelfService/Web/containerregistry/container.tsx
  Source/SelfService/Web/containerregistry/welcome.tsx
  Source/SelfService/Web/customer/create.tsx
  Source/SelfService/Web/customer/view.tsx
  Source/SelfService/Web/customer/viewAll.tsx
  Source/SelfService/Web/documentation/cicd/setupAzurePipelines.tsx
  Source/SelfService/Web/documentation/container.tsx
  Source/SelfService/Web/insights/container.tsx
  Source/SelfService/Web/insights/runtimeStatsV1/runtimeV1Stats.tsx
  Source/SelfService/Web/m3connector/container.tsx
  Source/SelfService/Web/m3connector/details.tsx
  Source/SelfService/Web/m3connector/overview.tsx
  Source/SelfService/Web/microservice/base/configuration.tsx
  Source/SelfService/Web/microservice/base/create.tsx
  Source/SelfService/Web/microservice/base/liveIngressView.tsx
  Source/SelfService/Web/microservice/base/view.tsx
  Source/SelfService/Web/microservice/components/headDataRow.tsx
  Source/SelfService/Web/microservice/create.tsx
  Source/SelfService/Web/microservice/create/card.tsx
  Source/SelfService/Web/microservice/delete.tsx
  Source/SelfService/Web/microservice/environmentVariables/view.tsx
  Source/SelfService/Web/microservice/microserviceEditScreen.tsx
  Source/SelfService/Web/microservice/overview.tsx
  Source/SelfService/Web/microservice/podLogScreen.tsx
  Source/SelfService/Web/microservice/purchaseOrder/configuration.tsx
  Source/SelfService/Web/microservice/purchaseOrder/create.tsx
  Source/SelfService/Web/microservice/purchaseOrder/editWebhookCredentials.tsx
  Source/SelfService/Web/microservice/purchaseOrder/view.tsx
  Source/SelfService/Web/microservice/purchaseOrder/viewWebhookCredentials.tsx
  Source/SelfService/Web/microservice/rawDataLog/view.tsx
  Source/SelfService/Web/microservice/staticSite/create.tsx
  Source/SelfService/Web/microservice/view.tsx
  Source/SelfService/Web/microservice/viewCard.tsx
  Source/SelfService/Web/screens/adminScreen.tsx
  Source/SelfService/Web/screens/applicationsScreen.tsx
  Source/SelfService/Web/screens/backupsScreen.tsx
  Source/SelfService/Web/screens/containerRegistryScreen.tsx
  Source/SelfService/Web/screens/documentationScreen.tsx
  Source/SelfService/Web/screens/insightsScreen.tsx
  Source/SelfService/Web/screens/m3connectorScreen.tsx
  Source/SelfService/Web/screens/microservicesScreen.tsx
  Source/SelfService/Web/screens/themeScreen.tsx
  Source/SelfService/Web/screens/todoScreen.tsx
  Source/SelfService/Web/theme/theme.ts
Labels: minor

#196 Logs view minor adjustments
  Source/SelfService/Web/App.tsx
  Source/SelfService/Web/logging/logFilter/logFilterPanel.tsx
  Source/SelfService/Web/logging/logPanel.tsx
  Source/SelfService/Web/package.json
  Source/SelfService/Web/screens/logsScreen.tsx
  Source/SelfService/Web/theme/theme.ts
  yarn.lock
Labels: patch
