Repository dolittle/Studio, pull requests merged in 2023-03, with the labels that each got.

#319 ADR describing the immediate focus on Bridge / Integrations module
  Documentation/adr/0002-immediate-focus-on-integrations-mvp.md
Labels: no-release

#324 Introduce SET_HEADERS env var for configuring headers to be set
  Source/SelfService/Backend/main.go
  Source/SelfService/Backend/main_test.go
Labels: minor

#332 add descriptions to individual button stories
  Source/DesignSystem/atoms/Button/Button.stories.tsx
  Source/DesignSystem/atoms/Button/helpers.ts
Labels: patch

#333 Dummy component template
  Source/DesignSystem/atoms/StoryTemplate/StoryTemplate.stories.tsx
Labels: patch

#337 Add card component to Design System
  Source/DesignSystem/atoms/SimpleCard/SimpleCard.stories.tsx
  Source/DesignSystem/atoms/SimpleCard/SimpleCard.tsx
  Source/DesignSystem/atoms/SimpleCard/index.ts
  Source/DesignSystem/index.ts
Labels: patch

#338 Component guideline updates
  Source/DesignSystem/StoryTemplate/StoryTemplate.stories.tsx
  Source/DesignSystem/atoms/AlertBox/AlertBox.stories.tsx
  Source/DesignSystem/atoms/AlertBox/helpers.tsx
  Source/DesignSystem/atoms/AlertDialog/AlertDialog.stories.tsx
  Source/DesignSystem/atoms/AlertDialog/helpers.ts
  Source/DesignSystem/atoms/Button/Button.stories.tsx
  Source/DesignSystem/atoms/Forms/Checkbox.stories.tsx
  Source/DesignSystem/atoms/Forms/Input.stories.tsx
  Source/DesignSystem/atoms/Forms/Select.stories.tsx
  Source/DesignSystem/atoms/Forms/Switch.stories.tsx
  Source/DesignSystem/atoms/Icon/Icon.stories.tsx
  Source/DesignSystem/atoms/IconButton/IconButton.stories.tsx
  Source/DesignSystem/atoms/LoadingSpinner/LoadingSpinner.stories.tsx
  Source/DesignSystem/atoms/Snackbar/Snackbar.stories.tsx
  Source/DesignSystem/atoms/Tabs/Tabs.stories.tsx
  Source/DesignSystem/atoms/Tooltip/Tooltip.stories.tsx
Labels: patch

#348 Update generated api files
  Source/SelfService/Web/apis/integrations/generated/.openapi-generator/FILES
  Source/SelfService/Web/apis/integrations/generated/apis/ConfigurationApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/ConnectionConfigurationApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/ConnectionsApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/DeploymentApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/EnvironmentApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/MessageMappingApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/ProgramMetadataApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/TableMetadataApi.ts
  Source/SelfService/Web/apis/integrations/generated/apis/index.ts
  Source/SelfService/Web/apis/integrations/generated/models/ConnectionModel.ts
  Source/SelfService/Web/apis/integrations/generated/models/IonConfigDto.ts
  Source/SelfService/Web/apis/integrations/generated/models/MessageMappingModel.ts
  Source/SelfService/Web/apis/integrations/generated/models/MessageMappingModelResult.ts
  Source/SelfService/Web/apis/integrations/generated/models/MetadataPublisherConfigDto.ts
  Source/SelfService/Web/apis/integrations/generated/models/RemoteServiceStatus.ts
  Source/SelfService/Web/apis/integrations/generated/models/index.ts
Labels: patch
